services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: claims-module-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Local_dev_password_123!"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - claims-module-sqlserver-data:/var/opt/mssql

volumes:
  claims-module-sqlserver-data:
